# Required API keys
PINECONE_API_KEY = "enter your key here"
GOOGLE_API_KEY = "enter your key here"
PINECONE_HOST = "enter your key here" 

# Optional LangSmith configuration (for advanced monitoring)
LANGCHAIN_API_KEY = "enter your key here"
LANGCHAIN_PROJECT = "pdf-chatbot"
LANGCHAIN_TRACING_V2 = "true"
